# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'

services:
  notification:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  countryconfig:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:${COUNTRY_CONFIG_VERSION:-latest}
    restart: unless-stopped
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - NODE_ENV=production
      - FHIR_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - OPENHIM_URL=http://openhim-core:5001/fhir
      - CONFIRM_REGISTRATION_URL=http://openhim-core:5001/confirm/registration
      - CHECK_INVALID_TOKEN=true
      - HOSTNAME=${HOSTNAME}
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

    deploy:
      replicas: 1
    networks:
      - overlay_net

  client:
    environment:
      - DECLARED_DECLARATION_SEARCH_QUERY_COUNT = 100

  gateway:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604
      - NATIONAL_ID_OIDP_BASE_URL=https://idp-mock.collab.mosip.net/

  workflow:
    environment:
      - LANGUAGES=en,fr
      - MOSIP_TOKEN_SEEDER_URL=http://mosiptokenseeder:8080
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  auth:
    environment:
      - QA_ENV=true
      - NODE_ENV=production
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  user-mgnt:
    environment:
      - QA_ENV=true
      - NODE_ENV=production
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604
      - NATIONAL_ID_OIDP_BASE_URL=https://idp-mock.collab.mosip.net/
      - NATIONAL_ID_OIDP_CLIENT_ID=3yz7-j3xRzU3SODdoNgSGvO_cD8UijH3AIWRDAg1x-M
      - NATIONAL_ID_OIDP_ESSENTIAL_CLAIMS=name,address,phone_number,email,gender,birthdate
  
  config:
    environment:
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  metrics:
    environment:
      - QA_ENV=true
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  search:
    environment:
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604

  webhooks:
    environment:
      - SENTRY_DSN=https://f892d643aab642108f44e2d1795706bc@o309867.ingest.sentry.io/1774604
  
  mosiptokenseeder:
    image: mosipdev/mosip-token-seeder:develop
    ports:
      - '8085:8080'
    deploy:
      replicas: 1
    networks:
      - overlay_net
    volumes:
      - /data/secrets/mosip:/seeder/certs
    restart: unless-stopped
    environment:
      - TOKENSEEDER_MOSIP_AUTH__PARTNER_APIKEY=${TOKENSEEDER_MOSIP_AUTH__PARTNER_APIKEY}
      - TOKENSEEDER_MOSIP_AUTH__PARTNER_MISP_LK=${TOKENSEEDER_MOSIP_AUTH__PARTNER_MISP_LK}
      - TOKENSEEDER_MOSIP_AUTH__PARTNER_ID=opencrvs-auth-partner
      - TOKENSEEDER_MOSIP_AUTH_SERVER__IDA_AUTH_DOMAIN_URI=https://api-internal.mec.mosip.net
      - TOKENSEEDER_MOSIP_AUTH_SERVER__IDA_AUTH_URL=https://api.mec.mosip.net/idauthentication/v1/auth
      - TOKENSEEDER_CRYPTO_SIGNATURE__SIGN_P12_FILE_PASSWORD=${TOKENSEEDER_CRYPTO_SIGNATURE__SIGN_P12_FILE_PASSWORD}
      - TOKENSEEDER_AUTHTOKEN__MANDATORY_VALIDATION_AUTH_FIELDS="name,gender,dob"
      - TOKENSEEDER_CRYPTO_ENCRYPT__ENCRYPT_CERT_PATH=/seeder/certs/ida.partner.crt
      - TOKENSEEDER_CRYPTO_SIGNATURE__SIGN_P12_FILE_PATH=/seeder/certs/keystore.p12
      - TOKENSEEDER_ROOT__SYNC_OPERATION_MODE=true

secrets:
  openhim-user:
    external: true
  openhim-password:
    external: true
