# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'

services:
  notification:
    environment:
      - LANGUAGES=en

  countryconfig:
    image: opencrvs/ocrvs-farajaland:${COUNTRY_CONFIG_VERSION:-latest}
    restart: unless-stopped
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - NODE_ENV=production
      - FHIR_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - OPENHIM_URL=http://openhim-core:5001/fhir
      - CONFIRM_REGISTRATION_URL=http://workflow:5050/confirm/registration
      - CHECK_INVALID_TOKEN=true
      - CERT_PUBLIC_KEY_PATH=/run/secrets/jwt-public-key.{{ts}}
      - MONGO_URL=mongodb://mongo1,mongo2,mongo3/user-mgnt?replicaSet=rs0
      - CONFIG_MONGO_URL=mongodb://mongo1,mongo2,mongo3/application-config?replicaSet=rs0
      - HOSTNAME=${HOSTNAME}

    deploy:
      replicas: 1
    networks:
      - overlay_net

  client:
    environment:
      - DECLARED_DECLARATION_SEARCH_QUERY_COUNT = 100

  gateway:
    environment:
      - LANGUAGES=en

  workflow:
    environment:
      - LANGUAGES=en

  auth:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  user-mgnt:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

secrets:
  jwt-public-key.{{ts}}:
    external: true
  openhim-user:
    external: true
  openhim-password:
    external: true
  clickatell-user:
    external: true
  clickatell-password:
    external: true
  clickatell-api-id:
    external: true
