# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
name: Generate demo data

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run from'
        required: false
        default: 'develop'
      districts:
        description: 'District ids separated by comma'
        required: false
      environment:
        type: choice
        description: Environment to deploy to
        required: true
        options:
          - production
          - qa
          - staging

jobs:
  manual-deploy-staging-e2e:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.17.0]
    steps:
      - name: Checking out git repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Install dependencies
        run: yarn install
      - name: Start generating test data
        run: yarn data-generator
        env:
          DISTRICTS: ${{ github.event.inputs.districts }}
          COUNTRY_CONFIG_HOST: ${{ secrets.COUNTRY_CONFIG_HOST }}
          AUTH_API_HOST: ${{ secrets.AUTH_API_HOST }}
          GATEWAY_HOST: ${{ secrets.GATEWAY_HOST }}
          CONCURRENCY: ${{ secrets.CONCURRENCY }}
